syntax = "proto3";
package RoboMaster;

// 定义 RemoteControl (发送给服务器) - 对应文档 Page 52
message RemoteControl { 
    int32 mouse_x = 1; 
    int32 mouse_y = 2; 
    int32 mouse_z = 3; 
    bool left_button_down = 4; 
    bool right_button_down = 5; 
    uint32 keyboard_value = 6; 
    bool mid_button_down = 7; 
    bytes data = 8; 
} 

// 定义 GameStatus (接收) - 对应文档 Page 53
message GameStatus { 
    uint32 current_round = 1; 
    uint32 total_rounds = 2; 
    uint32 red_score = 3; 
    uint32 blue_score = 4; 
    uint32 current_stage = 5; 
    int32 stage_countdown_sec = 6; 
    int32 stage_elapsed_sec = 7; 
    bool is_paused = 8; 
} 

// 定义 RobotDynamicStatus (接收) - 对应文档 Page 61
message RobotDynamicStatus { 
    uint32 current_health = 1; 
    float current_heat = 2; 
    float last_projectile_fire_rate = 3; 
    uint32 current_chassis_energy = 4; 
    uint32 current_buffer_energy = 5; 
    uint32 current_experience = 6; 
    uint32 experience_for_upgrade = 7; 
    uint32 total_projectiles_fired = 8; 
    uint32 remaining_ammo = 9; 
    bool is_out_of_combat = 10; 
    uint32 out_of_combat_countdown = 11; 
    bool can_remote_heal = 12; 
    bool can_remote_ammo = 13;
}